---

DATA_DIR: "data"
LEARNING_RATE: 2e-4
BATCH_SIZE: 64
IMAGE_SIZE: 64
NUM_CHANNELS: 3
NOISE_DIM: 100
NUM_EPOCHS: 30
FEATURES_DISC: 64
FEATURES_GEN: 64
FROM_CHECKPOINT: True
CHECKPOINT_PATH: "checkpoints"
LOG_PATH: "logs"
