---

DATA_DIR: "../data"
LEARNING_RATE: 2e-4
BATCH_SIZE: 64
IMAGE_SIZE: 64
NUM_CHANNELS: 3
NOISE_DIM: 100
NUM_EPOCHS: 50
FEATURES_CRIT: 64
FEATURES_GEN: 64
FROM_CHECKPOINT: False
CHECKPOINT_PATH: "checkpoints"
LOG_PATH: "logs"

BETA_1: 0.5
BETA_2: 0.999
C_LAMBDA: 10
CRIT_REPEATS: 5